#!/usr/bin/env bash
# a shell ro print some info of the server
domain=$1
subdomain=$2
there_is_sub () {
	rec=$(dig $2.$1 | grep -A1 "ANSWER SECTION:" | awk '{print $4}')
        des=$(dig $2.$1 | grep -A1 "ANSWER SECTION:" | awk '{print $5}')
        ser="The subdomain $2 is a ${rec} record and points to ${des}"
        echo $ser
}
if [ -z "$subdomain" ]
then
	there_is_sub $1 "www"
	there_is_sub $1 "lb-01"
	there_is_sub $1 "web-01"
	there_is_sub $1 "web-02"
else
	there_is_sub $1 $2
fi
