#!/usr/bin/env bash
#listen to port 80 instead of 8080
if ! command -v nginx &> /dev/null
then
    sudo apt-get update
    sudo apt-get install -y nginx
fi
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
