#!/usr/bin/env bash
#listen to port 80 instead of 8080
#!/usr/bin/env bash

if ! command -v nginx &> /dev/null
then
    sudo apt-get update
    sudo apt-get install -y nginx
fi

sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/default.bak


sudo sed -i 's/listen 8080;/listen 80;/g' /etc/nginx/sites-enabled/default

sudo systemctl restart nginx
