#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 and:
I=1
while [ $I -lt 21 ]
do
	case "$I" in
		4)
			echo $I
			echo "bad luck from China" ;;
		9)
			echo $I
			echo "bad luck from Japan" ;;
		17)
			echo $I
			echo "bad luck from Italy" ;;
		*)
			echo $I
	esac
	((I++))
done
